### PR TITLE
#6 Create .npmignore file

### PR DESCRIPTION
**Pull request by Voles**
See #6

### CODE REVIEW

**Comment by Voles** [comment]
Thanks for your work by the way! I hope this can resolve some of the long outstanding issues.

**Comment by stephenwvickers** [comment]
Thanks, the Travis CI file has gone now, and the tst directory will be renamed - I already have an ignore file I use so instead of merging this pull request I will manually add and then close this.

Out of interest, why wouldn't you want the test files included - my default disposition would be to include them to allow users to run tests on their own platform?

**Comment by stephenwvickers** [comment]
Hi @Voles,

I've added an .npmignore which is quite basic for now.  I will close this pull request.

I normally like to include tests in the published package on npm, if you have a compelling argument against this let me know via a new ticket and we can discuss further.

Many thanks

Steve

**Comment by Voles** [comment]
@stephenwvickers I don't really have an argument to keep the test-files NOT in the published package. The main reason to exclude as much files as possible is to keep the download size small and transfers as fast as possible. This is especially important in the Node ecosystem, where people tend to use many small modules. If people want to take a look at the tests, they would clone the module's repository.

The structure of the repository has changed and my proposal was outdated. Thanks for your copy!

**Pull request closed without merging**
